const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.jumpthru,
		C3.Behaviors.LOS,
		C3.Behaviors.Follow,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Follow.Acts.SetMode,
		C3.Behaviors.Follow.Acts.SetDelay,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{jogador: 0},
	{contador: 0},
	{Sólido: 0},
	{pizza1: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{Teclado: 0},
	{Sprite: 0},
	{jogador_pulo: 0},
	{PlanoDeFundoEmBlocos9: 0},
	{pizza2: 0},
	{pizza3: 0},
	{pizza4: 0},
	{rua1: 0},
	{rua2: 0},
	{rua3: 0},
	{buraco: 0},
	{buracoFundo: 0},
	{textoMorte: 0},
	{Áudio: 0},
	{fundoNoite: 0},
	{tempo: 0},
	{fundoCidade: 0},
	{PularAtravés: 0},
	{plataformasCidade: 0},
	{PosteNovo: 0},
	{lixeiraFinalizasda: 0},
	{Sprite2: 0},
	{imgDerrota: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Sprite6: 0},
	{PlanoDeFundoEmBlocos: 0},
	{CampoDeVisão: 0},
	{mendiga: 0},
	{Sprite8: 0},
	{Seguir: 0},
	{Projétil: 0},
	{garrafa: 0},
	{Sprite7: 0},
	{Mouse: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite9: 0},
	{Botão: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Texto: 0},
	{Texto2: 0},
	{mendiga2: 0},
	{boss: 0},
	{esgoto: 0},
	{Sprite14: 0},
	{tempoRestante: 0},
	{pos: 0},
	{ultimoCenario: 0},
	{portal: 0}
];

self.InstanceType = {
	jogador: class extends self.ISpriteInstance {},
	contador: class extends self.ITextInstance {},
	pizza1: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	jogador_pulo: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos9: class extends self.ITiledBackgroundInstance {},
	pizza2: class extends self.ISpriteInstance {},
	pizza3: class extends self.ISpriteInstance {},
	pizza4: class extends self.ISpriteInstance {},
	rua1: class extends self.ITiledBackgroundInstance {},
	rua2: class extends self.ITiledBackgroundInstance {},
	rua3: class extends self.ITiledBackgroundInstance {},
	buraco: class extends self.ITiledBackgroundInstance {},
	buracoFundo: class extends self.ITiledBackgroundInstance {},
	textoMorte: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	fundoNoite: class extends self.ITiledBackgroundInstance {},
	tempo: class extends self.ITextInstance {},
	fundoCidade: class extends self.ITiledBackgroundInstance {},
	plataformasCidade: class extends self.ITiledBackgroundInstance {},
	PosteNovo: class extends self.ISpriteInstance {},
	lixeiraFinalizasda: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	imgDerrota: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	mendiga: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	garrafa: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	mendiga2: class extends self.ISpriteInstance {},
	boss: class extends self.ISpriteInstance {},
	esgoto: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {}
}